language: php

php:
    - 5.6
    - 7.0
    - 7.1


before_install:
    - composer self-update

install:
    - composer install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -f coverage.xml